### PR TITLE
Port to MathComp 2

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by vbgl** [comment]
Is there a way to have a version that is compatible both with 1.7 and 2.0?

**Comment by proux01** [comment]
Not easily, this has been done in Interval using autoconf and duplicated files, I wouldn't recommend it.

**Comment by strub** [comment]
I assume that the PR should adapt the CI configuration to only test with MC2

**Comment by proux01** [comment]
Here is an attempt to do it.

**Comment by vbgl** [comment]
Thanks Pierre. I’ll take care of this PR promptly.

**Comment by proux01** [comment]
Thanks, we expect MC Analysis to switch to mathcomp 2 in the coming months (let's say January 2024) so if Jasmin could do so in a similar timeframe, that would be great.

**Comment by proux01** [comment]
@vbgl I should have think about it before merge but are you sure this doesn't require some adaptation in Coq CI?

**Pull request merged**
