### PR TITLE
Do not require all_ssreflect

### PR DESCRIPTION
**Pull request by vbgl**

### CODE REVIEW

**Review by strub — APPROVED** [review]
I assume this is for performance issues?

**Comment by vbgl** [comment]
That’s right. There is a bit of discussion there: https://github.com/jasmin-lang/jasmin/pull/560#issuecomment-2124109371

Probably this is not very useful but it cannot harm.

**Comment by gares** [comment]
So, if these files get a speedup, then you should merge.

But note that Import is not transitive: If these files don't get a speedup, it won't make users of these files faster...

**Comment by vbgl** [comment]
I’m not sure how to get performance measurements out of the dune build. Running `dune build --trace-file trace` both before and after this commit showed me a witness of a performance improvement of a few milliseconds.

**Pull request closed without merging**
